create table PRODUCT(PRODUCT_NO VARCHAR(15) NOT NULL PRIMARY KEY, DESCRIPTION VARCHAR(50) NOT NULL, COMPANY VARCHAR(15) NOT NULL, PRICE INT NOT NULL);

create table SUPPLIER(S_NO varchar(10) not null primary key, SNAME varchar(15) not null, AGE int not null , CITY
varchar(15) not null);

create table CUSTOMER(CUST_NO VARCHAR(15) NOT NULL PRIMARY KEY, NAME VARCHAR(15) NOT NULL, AGE INT NOT NULL, CITY VARCHAR(15) NOT NULL, PINCODE INT NOT NULL, STATE VARCHAR(15) NOT NULL);

create table PURCHASE (ORDER_NO varchar(15) not null primary key, CUSTNO varchar(15) not null, PRODNO varchar(15) not null,QUANTITY int not null , ORDERDATE date, foreign key(CUSTNO) references CUSTOMER(CUST_NO) on delete cascade, foreign key(PRODNO) references PRODUCT(PRODUCT_NO) on delete cascade);

desc PRODUCT;
desc SUPPLIER;
desc CUSTOMER;
desc PURCHASE;

INSERT INTO PRODUCT(PRODUCT_NO, DESCRIPTION, COMPANY, PRICE) VALUES('P00001', '12 W Flood Light', 'Wipro', 5000);
INSERT INTO PRODUCT(PRODUCT_NO, DESCRIPTION, COMPANY, PRICE) VALUES('P00002', 'Laptop Adapter', 'Dell', 1560);
INSERT INTO PRODUCT(PRODUCT_NO, DESCRIPTION, COMPANY, PRICE) VALUES('P00003', 'Tablet', 'HCL', 11000);
INSERT INTO PRODUCT(PRODUCT_NO, DESCRIPTION, COMPANY, PRICE) VALUES('P00004', 'Garnet 50W led', 'Wipro', 999);
INSERT INTO PRODUCT(PRODUCT_NO, DESCRIPTION, COMPANY, PRICE) VALUES('P00005', 'Laptop Charger', 'HCL', 1690);

INSERT INTO SUPPLIER(S_NO, SNAME, AGE, CITY) VALUES('S001', 'Ivan Bayross', 35, 'Bombay');
INSERT INTO SUPPLIER(S_NO, SNAME, AGE, CITY) VALUES('S002', 'Nirmala Agarwal', 35, 'Madras');
INSERT INTO SUPPLIER(S_NO, SNAME, AGE, CITY) VALUES('C003', 'Susmitha', 55, 'Bombay');
INSERT INTO SUPPLIER(S_NO, SNAME, AGE, CITY) VALUES('C004', 'Basu Navindgi', 45, 'Bombay');
INSERT INTO SUPPLIER(S_NO, SNAME, AGE, CITY) VALUES('C005', 'Ravi Sreedharan', 25, 'Delhi');
INSERT INTO SUPPLIER(S_NO, SNAME, AGE, CITY) VALUES('C006', 'Nanda Gopal', 25, 'Madras');

INSERT INTO CUSTOMER(CUST_NO, NAME, AGE, CITY, PINCODE, STATE) VALUES('C00001', 'Ivan Bayross', 35, 'Bombay', 400054, 'Maharashtra');
INSERT INTO CUSTOMER(CUST_NO, NAME, AGE, CITY, PINCODE, STATE) VALUES('C00002', 'Vandana Saitwal', 35, 'Madras', 780001, 'Tamilnadu');
INSERT INTO CUSTOMER(CUST_NO, NAME, AGE, CITY, PINCODE, STATE) VALUES('C00003', 'Pramada Jaguste', 55, 'Bombay', 400057, 'Maharashtra');
INSERT INTO CUSTOMER(CUST_NO, NAME, AGE, CITY, PINCODE, STATE) VALUES('C00004', 'Basu Navindgi', 45, 'Bombay', 400056, 'Maharashtra');
INSERT INTO CUSTOMER(CUST_NO, NAME, AGE, CITY, PINCODE, STATE) VALUES('C00005', 'Ravi Sreedharan', 25, 'Delhi', 100001, 'Delhi');
INSERT INTO CUSTOMER(CUST_NO, NAME, AGE, CITY, PINCODE, STATE) VALUES('C00006', 'Rukmini', 25, 'Madras', 780001, 'Tamilnadu');

